In [2]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
df=pd.read_csv('/content/bollywood_movies_with_actors (2).csv')
df.head()

IMDb_ID                            Title    Year  \
0  tt15354916                            Jawan  2023.0   
1  tt15748830                       Jaane Jaan  2023.0   
2  tt11663228                           Jailer  2023.0   
3  tt14993250  Rocky Aur Rani Kii Prem Kahaani  2023.0   
4  tt15732324                            OMG 2  2023.0   

                                       Genres  \
0                     Action, Crime, Thriller   
1                      Crime, Thriller, Drama   
2  Action, Crime, Thriller, Comedy, Adventure   
3              Comedy, Drama, Family, Romance   
4                               Comedy, Drama   

                                              Actors  \
0  Shah Rukh Khan, Nayanthara, Vijay Sethupathi, ...   
1  Kareena Kapoor Khan, Jaideep Ahlawat, Vijay Va...   
2  Rajinikanth, Vinayakan, Vasanth Ravi, Yogi Bab...   
3  Alia Bhatt, Ranveer Singh, Jaya Bachchan, Shab...   
4  Pankaj Tripathi, Akshay Kumar, Yami Gautam, Pa...   

                                            Overview  Rating  \
0  An emotional journey of a prison warden, drive...   7.200   
1  When a single mother her teenage daughter beco...   7.117   
2  Muthuvel Pandian, a retired, stern yet compass...   6.700   
3  Gym-freak brat Rocky falls in love with Rani, ...   6.300   
4  Life is bliss until one day Kanti Sharan Mudga...   7.250   

                                          Poster_URL  \
0  https://image.tmdb.org/t/p/w500/ddAHq5R52rZSuT...   
1  https://image.tmdb.org/t/p/w500/oaUOV9VCNM5Mjr...   
2  https://image.tmdb.org/t/p/w500/pTmMxAHqX4vsID...   
3  https://image.tmdb.org/t/p/w500/vTQIqlxUkOuyf2...   
4  https://image.tmdb.org/t/p/w500/kApiO3oL6t100a...   

                                             Reviews  
0  I had a lot of fun watching **Jawan**. It is a...  
1  aane Jaan is a suspenseful rollercoaster ride ...  
2                                                NaN  
3                                                NaN  
4                                                NaN

In [4]:
df.shape

(2104, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2104 entries, 0 to 2103
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   IMDb_ID     2104 non-null   object 
 1   Title       2104 non-null   object 
 2   Year        2070 non-null   float64
 3   Genres      2029 non-null   object 
 4   Actors      2081 non-null   object 
 5   Overview    2081 non-null   object 
 6   Rating      2104 non-null   float64
 7   Poster_URL  2077 non-null   object 
 8   Reviews     138 non-null    object 
dtypes: float64(2), object(7)
memory usage: 148.1+ KB


In [7]:
selected_features=['Genres','Actors','Overview']
print(selected_features)

['Genres', 'Actors', 'Overview']


In [11]:
for featur in selected_features:
  df[featur]=df[featur].fillna('')

In [12]:
combine_feature=df['Genres']+df['Actors']+df['Overview']
print(combine_feature)

0       Action, Crime, ThrillerShah Rukh Khan, Nayanth...
1       Crime, Thriller, DramaKareena Kapoor Khan, Jai...
2       Action, Crime, Thriller, Comedy, AdventureRaji...
3       Comedy, Drama, Family, RomanceAlia Bhatt, Ranv...
4       Comedy, DramaPankaj Tripathi, Akshay Kumar, Ya...
                              ...                        
2099    Shatrughan Sinha, Reena Roy, Ajit Khan, Premna...
2100    DramaLucky Ali, Simone Singh, Achint Kaur, Div...
2101    Drama, RomanceSooraj Pancholi, Isabelle Kaif, ...
2102    Drama, Fantasy, HorrorSridevi, Sunny Deol, Anu...
2103    ComedyGovinda, Sushmita Sen, Rambha, Satish Ka...
Length: 2104, dtype: object


In [13]:
vectorizer=TfidfVectorizer()
vectors=vectorizer.fit_transform(combine_feature)
print(vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 95240 stored elements and shape (2104, 15972)>
  Coords	Values
  (0, 331)	0.06152878919204941
  (0, 3286)	0.07640164007732751
  (0, 14581)	0.17051490300674693
  (0, 12215)	0.1146160418758167
  (0, 7705)	0.06769711765277747
  (0, 9652)	0.1739791319710641
  (0, 15406)	0.10920572782408122
  (0, 12806)	0.17797829081626812
  (0, 3641)	0.1389577400672883
  (0, 10134)	0.138014247725716
  (0, 12438)	0.10951275128988908
  (0, 4560)	0.20647978725209504
  (0, 4713)	0.1647258496727722
  (0, 7330)	0.10830587414725314
  (0, 9930)	0.03860667050624195
  (0, 10850)	0.1389577400672883
  (0, 15593)	0.19596073293894214
  (0, 4479)	0.1739791319710641
  (0, 2263)	0.06534237948313264
  (0, 10449)	0.1362243532369453
  (0, 15327)	0.18849734512942098
  (0, 15696)	0.09589231560652062
  (0, 7668)	0.17797829081626812
  (0, 15153)	0.0802004644901817
  (0, 14708)	0.1401889484181507
  :	:
  (2103, 943)	0.09195629894138412
  (2103, 14052)	0.2624694773879191

In [15]:
similarity=cosine_similarity(vectors)
print(similarity)

[[1.         0.07724295 0.03554594 ... 0.02705108 0.01314039 0.0724895 ]
 [0.07724295 1.         0.05177126 ... 0.00435429 0.03901305 0.01622565]
 [0.03554594 0.05177126 1.         ... 0.03173814 0.01278695 0.05264802]
 ...
 [0.02705108 0.00435429 0.03173814 ... 1.         0.01196083 0.0163209 ]
 [0.01314039 0.03901305 0.01278695 ... 0.01196083 1.         0.03234933]
 [0.0724895  0.01622565 0.05264802 ... 0.0163209  0.03234933 1.        ]]


In [17]:
similarity.shape

(2104, 2104)

In [19]:
def recommend_movie(movie):
  index = df[df['Title'] == movie].index[0]
  distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
  for i in distances[1:6]:
      print(df.iloc[i[0]].Title)

In [22]:
recommend_movie('Satyaprem Ki Katha')

Luka Chuppi
Pati Patni Aur Woh
Good Newwz
Goliyon Ki Raasleela Ram-Leela
Bhool Bhulaiyaa 2


In [23]:
import pickle

# Save similarity matrix
with open('similarity.pkl', 'wb') as f:
    pickle.dump(similarity, f)

# Save dataframe with movie details
with open('movies_df.pkl', 'wb') as f:
    pickle.dump(df, f)
